### PR TITLE
fix!: compatibility with new cypress 10 configuration

### PR DESCRIPTION
**Pull request by Anthony-Champagne-Wiztivi**
related to #1 .

- reimplement resolveTestFiles w/o integrationFolder and with new specPattern / excludeSpecPattern
- update tests (replace integrationFolder with fixturesFolder for configuration resolving tests)
- update README
- bump 3.0.0

### CODE REVIEW

**Comment by badeball** [comment]
Hey @Anthony-Champagne-Wiztivi, thanks for your work in both this and badeball/cypress-cucumber-preprocessor/pull/734. This however isn't complete I'm afraid, as it does not take into account reading from the new `cypress.config.{js,mjs,ts}` and thus `resolveTestFiles()` will not behave correctly.

@lmiller1990 and @admah, is this something we can request that Cypress expose for us? Either a complete configuration resolvement or simply a method for resolving test files given [cwd, argv, env].

**Comment by badeball** [comment]
Bear in mind that this plugin powers https://github.com/badeball/cypress-parallel and an (hopefully) upcoming vscode extension for Cypress + Cucumber, both of which does not have the luxury of access to the `config` object as a regular Cypress plugin has.

**Comment by Anthony-Champagne-Wiztivi** [comment]
Thanks for your feedback @badeball ! TBH I was afraid of it... too much code in this package wasn't being accessed from the preprocessor. It all makes sense now with cypress-parallel :smile:

I'll take time this morning to see if I can take care of it manually, so that we can have a temporary solution before a resolver is available from the core ? Is it OK with you ?

**Comment by badeball** [comment]
> I'll take time this morning to see if I can take care of it manually, so that we can have a temporary solution before a resolver is available from the core ? Is it OK with you ?

I'm also not entirely sure what you have in mind, but I'm afraid we might not be on the same wavelength as to how to implement support for v10.

It shouldn't come as a surprise, but I don't intend to remove support for < 10 during this. You should keep this is mind if you want to continue the work without my counsil. Otherwise you run the risk of disappointment, as I'm not going to merge something hastily.

**Comment by Anthony-Champagne-Wiztivi** [comment]
OK thanks for the quick reply, I'll wait for you to do the work then ;)

**Comment by badeball** [comment]
This has been superseded by https://github.com/badeball/cypress-configuration/commit/d2ea63cf12c8d4546f00e17a50261733997d6b5c, where I ensured to retain backward compatibility.

**Pull request closed without merging**
